export interface plant {
    plant_name : string,
    minTemp_day : number,
    maxTemp_day : number,    
    minTemp_night : number,
    maxTemp_night : number,
    minHumidity : number,
    maxHumidity: number,
    Wind : string, // Low, Moderate, High
    minUVIndex : number,
    maxUVIndex : number,
    minLight : number,
    maxLight : number,
    minSoilMoisture : number,
    maxSoilMoisture : number,
    lastDateOfIrrigation : string,
    lastDateOfFertilizer : string,
    lastDateOfPesticide : string,
    lastDateOfNutrients : string,
}